//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectServer.usergraph {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="binario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class binario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.usergraph.usuario raizField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.usergraph.usuario raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.usergraph.usuario raizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.usergraph.usuario izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.usergraph.usuario derField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.usergraph.usuario raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ProyectServer.usergraph.usuario izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.usergraph.usuario der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="usergraph.graficarusuariosSoap")]
    public interface graficarusuariosSoap {
        
        // CODEGEN: Generating message contract since element name bin from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        ProyectServer.usergraph.graficarResponse graficar(ProyectServer.usergraph.graficarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.usergraph.graficarResponse> graficarAsync(ProyectServer.usergraph.graficarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.usergraph.graficarRequestBody Body;
        
        public graficarRequest() {
        }
        
        public graficarRequest(ProyectServer.usergraph.graficarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.usergraph.binario bin;
        
        public graficarRequestBody() {
        }
        
        public graficarRequestBody(ProyectServer.usergraph.binario bin) {
            this.bin = bin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.usergraph.graficarResponseBody Body;
        
        public graficarResponse() {
        }
        
        public graficarResponse(ProyectServer.usergraph.graficarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class graficarResponseBody {
        
        public graficarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface graficarusuariosSoapChannel : ProyectServer.usergraph.graficarusuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class graficarusuariosSoapClient : System.ServiceModel.ClientBase<ProyectServer.usergraph.graficarusuariosSoap>, ProyectServer.usergraph.graficarusuariosSoap {
        
        public graficarusuariosSoapClient() {
        }
        
        public graficarusuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public graficarusuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficarusuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficarusuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.usergraph.graficarResponse ProyectServer.usergraph.graficarusuariosSoap.graficar(ProyectServer.usergraph.graficarRequest request) {
            return base.Channel.graficar(request);
        }
        
        public void graficar(ProyectServer.usergraph.binario bin) {
            ProyectServer.usergraph.graficarRequest inValue = new ProyectServer.usergraph.graficarRequest();
            inValue.Body = new ProyectServer.usergraph.graficarRequestBody();
            inValue.Body.bin = bin;
            ProyectServer.usergraph.graficarResponse retVal = ((ProyectServer.usergraph.graficarusuariosSoap)(this)).graficar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.usergraph.graficarResponse> ProyectServer.usergraph.graficarusuariosSoap.graficarAsync(ProyectServer.usergraph.graficarRequest request) {
            return base.Channel.graficarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.usergraph.graficarResponse> graficarAsync(ProyectServer.usergraph.binario bin) {
            ProyectServer.usergraph.graficarRequest inValue = new ProyectServer.usergraph.graficarRequest();
            inValue.Body = new ProyectServer.usergraph.graficarRequestBody();
            inValue.Body.bin = bin;
            return ((ProyectServer.usergraph.graficarusuariosSoap)(this)).graficarAsync(inValue);
        }
    }
}
