//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectServer.graficarcontactos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="avl", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class avl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.nodoavl raizField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.graficarcontactos.nodoavl raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nodoavl", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class nodoavl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.usuario userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.nodoavl raizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.nodoavl izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.nodoavl derField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.graficarcontactos.usuario user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nick {
            get {
                return this.nickField;
            }
            set {
                if ((object.ReferenceEquals(this.nickField, value) != true)) {
                    this.nickField = value;
                    this.RaisePropertyChanged("nick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectServer.graficarcontactos.nodoavl raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectServer.graficarcontactos.nodoavl izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ProyectServer.graficarcontactos.nodoavl der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        private int conectadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.listajuegos listadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.avl contactosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.usuario raizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.usuario izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.usuario derField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int conectado {
            get {
                return this.conectadoField;
            }
            set {
                if ((this.conectadoField.Equals(value) != true)) {
                    this.conectadoField = value;
                    this.RaisePropertyChanged("conectado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.graficarcontactos.listajuegos listado {
            get {
                return this.listadoField;
            }
            set {
                if ((object.ReferenceEquals(this.listadoField, value) != true)) {
                    this.listadoField = value;
                    this.RaisePropertyChanged("listado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ProyectServer.graficarcontactos.avl contactos {
            get {
                return this.contactosField;
            }
            set {
                if ((object.ReferenceEquals(this.contactosField, value) != true)) {
                    this.contactosField = value;
                    this.RaisePropertyChanged("contactos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ProyectServer.graficarcontactos.usuario raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectServer.graficarcontactos.usuario izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ProyectServer.graficarcontactos.usuario der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="listajuegos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class listajuegos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.juego primeroField;
        
        private int contField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.graficarcontactos.juego primero {
            get {
                return this.primeroField;
            }
            set {
                if ((object.ReferenceEquals(this.primeroField, value) != true)) {
                    this.primeroField = value;
                    this.RaisePropertyChanged("primero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int cont {
            get {
                return this.contField;
            }
            set {
                if ((this.contField.Equals(value) != true)) {
                    this.contField = value;
                    this.RaisePropertyChanged("cont");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="juego", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class juego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userbaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oponenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.juego siguienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarcontactos.juego anteriorField;
        
        private int desplegadasField;
        
        private int sobrevivientesField;
        
        private int destruidasField;
        
        private int ganoField;
        
        private int contField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userbase {
            get {
                return this.userbaseField;
            }
            set {
                if ((object.ReferenceEquals(this.userbaseField, value) != true)) {
                    this.userbaseField = value;
                    this.RaisePropertyChanged("userbase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oponente {
            get {
                return this.oponenteField;
            }
            set {
                if ((object.ReferenceEquals(this.oponenteField, value) != true)) {
                    this.oponenteField = value;
                    this.RaisePropertyChanged("oponente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.graficarcontactos.juego siguiente {
            get {
                return this.siguienteField;
            }
            set {
                if ((object.ReferenceEquals(this.siguienteField, value) != true)) {
                    this.siguienteField = value;
                    this.RaisePropertyChanged("siguiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ProyectServer.graficarcontactos.juego anterior {
            get {
                return this.anteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.anteriorField, value) != true)) {
                    this.anteriorField = value;
                    this.RaisePropertyChanged("anterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int desplegadas {
            get {
                return this.desplegadasField;
            }
            set {
                if ((this.desplegadasField.Equals(value) != true)) {
                    this.desplegadasField = value;
                    this.RaisePropertyChanged("desplegadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int sobrevivientes {
            get {
                return this.sobrevivientesField;
            }
            set {
                if ((this.sobrevivientesField.Equals(value) != true)) {
                    this.sobrevivientesField = value;
                    this.RaisePropertyChanged("sobrevivientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int destruidas {
            get {
                return this.destruidasField;
            }
            set {
                if ((this.destruidasField.Equals(value) != true)) {
                    this.destruidasField = value;
                    this.RaisePropertyChanged("destruidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int gano {
            get {
                return this.ganoField;
            }
            set {
                if ((this.ganoField.Equals(value) != true)) {
                    this.ganoField = value;
                    this.RaisePropertyChanged("gano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int cont {
            get {
                return this.contField;
            }
            set {
                if ((this.contField.Equals(value) != true)) {
                    this.contField = value;
                    this.RaisePropertyChanged("cont");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="graficarcontactos.graficaravlSoap")]
    public interface graficaravlSoap {
        
        // CODEGEN: Generating message contract since element name arbol from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        ProyectServer.graficarcontactos.graficarResponse graficar(ProyectServer.graficarcontactos.graficarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.graficarcontactos.graficarResponse> graficarAsync(ProyectServer.graficarcontactos.graficarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.graficarcontactos.graficarRequestBody Body;
        
        public graficarRequest() {
        }
        
        public graficarRequest(ProyectServer.graficarcontactos.graficarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.graficarcontactos.avl arbol;
        
        public graficarRequestBody() {
        }
        
        public graficarRequestBody(ProyectServer.graficarcontactos.avl arbol) {
            this.arbol = arbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.graficarcontactos.graficarResponseBody Body;
        
        public graficarResponse() {
        }
        
        public graficarResponse(ProyectServer.graficarcontactos.graficarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string graficarResult;
        
        public graficarResponseBody() {
        }
        
        public graficarResponseBody(string graficarResult) {
            this.graficarResult = graficarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface graficaravlSoapChannel : ProyectServer.graficarcontactos.graficaravlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class graficaravlSoapClient : System.ServiceModel.ClientBase<ProyectServer.graficarcontactos.graficaravlSoap>, ProyectServer.graficarcontactos.graficaravlSoap {
        
        public graficaravlSoapClient() {
        }
        
        public graficaravlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public graficaravlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficaravlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficaravlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.graficarcontactos.graficarResponse ProyectServer.graficarcontactos.graficaravlSoap.graficar(ProyectServer.graficarcontactos.graficarRequest request) {
            return base.Channel.graficar(request);
        }
        
        public string graficar(ProyectServer.graficarcontactos.avl arbol) {
            ProyectServer.graficarcontactos.graficarRequest inValue = new ProyectServer.graficarcontactos.graficarRequest();
            inValue.Body = new ProyectServer.graficarcontactos.graficarRequestBody();
            inValue.Body.arbol = arbol;
            ProyectServer.graficarcontactos.graficarResponse retVal = ((ProyectServer.graficarcontactos.graficaravlSoap)(this)).graficar(inValue);
            return retVal.Body.graficarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.graficarcontactos.graficarResponse> ProyectServer.graficarcontactos.graficaravlSoap.graficarAsync(ProyectServer.graficarcontactos.graficarRequest request) {
            return base.Channel.graficarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.graficarcontactos.graficarResponse> graficarAsync(ProyectServer.graficarcontactos.avl arbol) {
            ProyectServer.graficarcontactos.graficarRequest inValue = new ProyectServer.graficarcontactos.graficarRequest();
            inValue.Body = new ProyectServer.graficarcontactos.graficarRequestBody();
            inValue.Body.arbol = arbol;
            return ((ProyectServer.graficarcontactos.graficaravlSoap)(this)).graficarAsync(inValue);
        }
    }
}
