//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectServer.graficarhistorial {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="arbolb", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class arbolb : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int gradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.nodob raizField;
        
        private int tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int grado {
            get {
                return this.gradoField;
            }
            set {
                if ((this.gradoField.Equals(value) != true)) {
                    this.gradoField = value;
                    this.RaisePropertyChanged("grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.graficarhistorial.nodob raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nodob", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class nodob : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.ArrayOfAtaque llavesField;
        
        private int gradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.ArrayOfNodob hijosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.nodob padreField;
        
        private int tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.graficarhistorial.ArrayOfAtaque llaves {
            get {
                return this.llavesField;
            }
            set {
                if ((object.ReferenceEquals(this.llavesField, value) != true)) {
                    this.llavesField = value;
                    this.RaisePropertyChanged("llaves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int grado {
            get {
                return this.gradoField;
            }
            set {
                if ((this.gradoField.Equals(value) != true)) {
                    this.gradoField = value;
                    this.RaisePropertyChanged("grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.graficarhistorial.ArrayOfNodob hijos {
            get {
                return this.hijosField;
            }
            set {
                if ((object.ReferenceEquals(this.hijosField, value) != true)) {
                    this.hijosField = value;
                    this.RaisePropertyChanged("hijos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ProyectServer.graficarhistorial.nodob padre {
            get {
                return this.padreField;
            }
            set {
                if ((object.ReferenceEquals(this.padreField, value) != true)) {
                    this.padreField = value;
                    this.RaisePropertyChanged("padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((this.tipoField.Equals(value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAtaque", Namespace="http://tempuri.org/", ItemName="ataque")]
    [System.SerializableAttribute()]
    public class ArrayOfAtaque : System.Collections.Generic.List<ProyectServer.graficarhistorial.ataque> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfNodob", Namespace="http://tempuri.org/", ItemName="nodob")]
    [System.SerializableAttribute()]
    public class ArrayOfNodob : System.Collections.Generic.List<ProyectServer.graficarhistorial.nodob> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ataque", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ataque : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int xField;
        
        private int yField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit atacanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit defensorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receptorField;
        
        private System.DateTime fechaField;
        
        private System.DateTime restanteField;
        
        private int contField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.graficarhistorial.unit atacante {
            get {
                return this.atacanteField;
            }
            set {
                if ((object.ReferenceEquals(this.atacanteField, value) != true)) {
                    this.atacanteField = value;
                    this.RaisePropertyChanged("atacante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ProyectServer.graficarhistorial.unit defensor {
            get {
                return this.defensorField;
            }
            set {
                if ((object.ReferenceEquals(this.defensorField, value) != true)) {
                    this.defensorField = value;
                    this.RaisePropertyChanged("defensor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string emisor {
            get {
                return this.emisorField;
            }
            set {
                if ((object.ReferenceEquals(this.emisorField, value) != true)) {
                    this.emisorField = value;
                    this.RaisePropertyChanged("emisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string receptor {
            get {
                return this.receptorField;
            }
            set {
                if ((object.ReferenceEquals(this.receptorField, value) != true)) {
                    this.receptorField = value;
                    this.RaisePropertyChanged("receptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime restante {
            get {
                return this.restanteField;
            }
            set {
                if ((this.restanteField.Equals(value) != true)) {
                    this.restanteField = value;
                    this.RaisePropertyChanged("restante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int cont {
            get {
                return this.contField;
            }
            set {
                if ((this.contField.Equals(value) != true)) {
                    this.contField = value;
                    this.RaisePropertyChanged("cont");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="unit", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class unit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        private int xField;
        
        private int yField;
        
        private int nivelField;
        
        private int movField;
        
        private int rminField;
        
        private int rmaxField;
        
        private int hpField;
        
        private int atkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        private int existeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit derField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit arribaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit abajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit supField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficarhistorial.unit infField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int nivel {
            get {
                return this.nivelField;
            }
            set {
                if ((this.nivelField.Equals(value) != true)) {
                    this.nivelField = value;
                    this.RaisePropertyChanged("nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int mov {
            get {
                return this.movField;
            }
            set {
                if ((this.movField.Equals(value) != true)) {
                    this.movField = value;
                    this.RaisePropertyChanged("mov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int rmin {
            get {
                return this.rminField;
            }
            set {
                if ((this.rminField.Equals(value) != true)) {
                    this.rminField = value;
                    this.RaisePropertyChanged("rmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int rmax {
            get {
                return this.rmaxField;
            }
            set {
                if ((this.rmaxField.Equals(value) != true)) {
                    this.rmaxField = value;
                    this.RaisePropertyChanged("rmax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int hp {
            get {
                return this.hpField;
            }
            set {
                if ((this.hpField.Equals(value) != true)) {
                    this.hpField = value;
                    this.RaisePropertyChanged("hp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int atk {
            get {
                return this.atkField;
            }
            set {
                if ((this.atkField.Equals(value) != true)) {
                    this.atkField = value;
                    this.RaisePropertyChanged("atk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int existe {
            get {
                return this.existeField;
            }
            set {
                if ((this.existeField.Equals(value) != true)) {
                    this.existeField = value;
                    this.RaisePropertyChanged("existe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ProyectServer.graficarhistorial.unit izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ProyectServer.graficarhistorial.unit der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ProyectServer.graficarhistorial.unit arriba {
            get {
                return this.arribaField;
            }
            set {
                if ((object.ReferenceEquals(this.arribaField, value) != true)) {
                    this.arribaField = value;
                    this.RaisePropertyChanged("arriba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ProyectServer.graficarhistorial.unit abajo {
            get {
                return this.abajoField;
            }
            set {
                if ((object.ReferenceEquals(this.abajoField, value) != true)) {
                    this.abajoField = value;
                    this.RaisePropertyChanged("abajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ProyectServer.graficarhistorial.unit sup {
            get {
                return this.supField;
            }
            set {
                if ((object.ReferenceEquals(this.supField, value) != true)) {
                    this.supField = value;
                    this.RaisePropertyChanged("sup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public ProyectServer.graficarhistorial.unit inf {
            get {
                return this.infField;
            }
            set {
                if ((object.ReferenceEquals(this.infField, value) != true)) {
                    this.infField = value;
                    this.RaisePropertyChanged("inf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="graficarhistorial.graficarbSoap")]
    public interface graficarbSoap {
        
        // CODEGEN: Generating message contract since element name arbol from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        ProyectServer.graficarhistorial.graficarResponse graficar(ProyectServer.graficarhistorial.graficarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.graficarhistorial.graficarResponse> graficarAsync(ProyectServer.graficarhistorial.graficarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.graficarhistorial.graficarRequestBody Body;
        
        public graficarRequest() {
        }
        
        public graficarRequest(ProyectServer.graficarhistorial.graficarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.graficarhistorial.arbolb arbol;
        
        public graficarRequestBody() {
        }
        
        public graficarRequestBody(ProyectServer.graficarhistorial.arbolb arbol) {
            this.arbol = arbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.graficarhistorial.graficarResponseBody Body;
        
        public graficarResponse() {
        }
        
        public graficarResponse(ProyectServer.graficarhistorial.graficarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string graficarResult;
        
        public graficarResponseBody() {
        }
        
        public graficarResponseBody(string graficarResult) {
            this.graficarResult = graficarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface graficarbSoapChannel : ProyectServer.graficarhistorial.graficarbSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class graficarbSoapClient : System.ServiceModel.ClientBase<ProyectServer.graficarhistorial.graficarbSoap>, ProyectServer.graficarhistorial.graficarbSoap {
        
        public graficarbSoapClient() {
        }
        
        public graficarbSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public graficarbSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficarbSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficarbSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.graficarhistorial.graficarResponse ProyectServer.graficarhistorial.graficarbSoap.graficar(ProyectServer.graficarhistorial.graficarRequest request) {
            return base.Channel.graficar(request);
        }
        
        public string graficar(ProyectServer.graficarhistorial.arbolb arbol) {
            ProyectServer.graficarhistorial.graficarRequest inValue = new ProyectServer.graficarhistorial.graficarRequest();
            inValue.Body = new ProyectServer.graficarhistorial.graficarRequestBody();
            inValue.Body.arbol = arbol;
            ProyectServer.graficarhistorial.graficarResponse retVal = ((ProyectServer.graficarhistorial.graficarbSoap)(this)).graficar(inValue);
            return retVal.Body.graficarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.graficarhistorial.graficarResponse> ProyectServer.graficarhistorial.graficarbSoap.graficarAsync(ProyectServer.graficarhistorial.graficarRequest request) {
            return base.Channel.graficarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.graficarhistorial.graficarResponse> graficarAsync(ProyectServer.graficarhistorial.arbolb arbol) {
            ProyectServer.graficarhistorial.graficarRequest inValue = new ProyectServer.graficarhistorial.graficarRequest();
            inValue.Body = new ProyectServer.graficarhistorial.graficarRequestBody();
            inValue.Body.arbol = arbol;
            return ((ProyectServer.graficarhistorial.graficarbSoap)(this)).graficarAsync(inValue);
        }
    }
}
