//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectServer.actualizaruser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.actualizaruser.usuario raizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.actualizaruser.usuario izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.actualizaruser.usuario derField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.actualizaruser.usuario raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ProyectServer.actualizaruser.usuario izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.actualizaruser.usuario der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="binario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class binario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.actualizaruser.usuario raizField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.actualizaruser.usuario raiz {
            get {
                return this.raizField;
            }
            set {
                if ((object.ReferenceEquals(this.raizField, value) != true)) {
                    this.raizField = value;
                    this.RaisePropertyChanged("raiz");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="actualizaruser.actualizarusuariosSoap")]
    public interface actualizarusuariosSoap {
        
        // CODEGEN: Generating message contract since element name user_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar", ReplyAction="*")]
        ProyectServer.actualizaruser.actualizarResponse actualizar(ProyectServer.actualizaruser.actualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.actualizarResponse> actualizarAsync(ProyectServer.actualizaruser.actualizarRequest request);
        
        // CODEGEN: Generating message contract since element name bin_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar", ReplyAction="*")]
        ProyectServer.actualizaruser.buscarResponse buscar(ProyectServer.actualizaruser.buscarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.buscarResponse> buscarAsync(ProyectServer.actualizaruser.buscarRequest request);
        
        // CODEGEN: Generating message contract since element name bin_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        ProyectServer.actualizaruser.insertarResponse insertar(ProyectServer.actualizaruser.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.insertarResponse> insertarAsync(ProyectServer.actualizaruser.insertarRequest request);
        
        // CODEGEN: Generating message contract since element name bin_ from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        ProyectServer.actualizaruser.eliminarResponse eliminar(ProyectServer.actualizaruser.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.eliminarResponse> eliminarAsync(ProyectServer.actualizaruser.eliminarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.actualizarRequestBody Body;
        
        public actualizarRequest() {
        }
        
        public actualizarRequest(ProyectServer.actualizaruser.actualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.usuario user_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nick_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass_;
        
        public actualizarRequestBody() {
        }
        
        public actualizarRequestBody(ProyectServer.actualizaruser.usuario user_, string nick_, string pass_) {
            this.user_ = user_;
            this.nick_ = nick_;
            this.pass_ = pass_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.actualizarResponseBody Body;
        
        public actualizarResponse() {
        }
        
        public actualizarResponse(ProyectServer.actualizaruser.actualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.usuario actualizarResult;
        
        public actualizarResponseBody() {
        }
        
        public actualizarResponseBody(ProyectServer.actualizaruser.usuario actualizarResult) {
            this.actualizarResult = actualizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.buscarRequestBody Body;
        
        public buscarRequest() {
        }
        
        public buscarRequest(ProyectServer.actualizaruser.buscarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.binario bin_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nick_;
        
        public buscarRequestBody() {
        }
        
        public buscarRequestBody(ProyectServer.actualizaruser.binario bin_, string nick_) {
            this.bin_ = bin_;
            this.nick_ = nick_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.buscarResponseBody Body;
        
        public buscarResponse() {
        }
        
        public buscarResponse(ProyectServer.actualizaruser.buscarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.usuario buscarResult;
        
        public buscarResponseBody() {
        }
        
        public buscarResponseBody(ProyectServer.actualizaruser.usuario buscarResult) {
            this.buscarResult = buscarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.insertarRequestBody Body;
        
        public insertarRequest() {
        }
        
        public insertarRequest(ProyectServer.actualizaruser.insertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.binario bin_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nick_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass_;
        
        public insertarRequestBody() {
        }
        
        public insertarRequestBody(ProyectServer.actualizaruser.binario bin_, string nick_, string pass_) {
            this.bin_ = bin_;
            this.nick_ = nick_;
            this.pass_ = pass_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.insertarResponseBody Body;
        
        public insertarResponse() {
        }
        
        public insertarResponse(ProyectServer.actualizaruser.insertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.binario insertarResult;
        
        public insertarResponseBody() {
        }
        
        public insertarResponseBody(ProyectServer.actualizaruser.binario insertarResult) {
            this.insertarResult = insertarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.eliminarRequestBody Body;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(ProyectServer.actualizaruser.eliminarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.binario bin_;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nick_;
        
        public eliminarRequestBody() {
        }
        
        public eliminarRequestBody(ProyectServer.actualizaruser.binario bin_, string nick_) {
            this.bin_ = bin_;
            this.nick_ = nick_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.actualizaruser.eliminarResponseBody Body;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(ProyectServer.actualizaruser.eliminarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.actualizaruser.binario eliminarResult;
        
        public eliminarResponseBody() {
        }
        
        public eliminarResponseBody(ProyectServer.actualizaruser.binario eliminarResult) {
            this.eliminarResult = eliminarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface actualizarusuariosSoapChannel : ProyectServer.actualizaruser.actualizarusuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class actualizarusuariosSoapClient : System.ServiceModel.ClientBase<ProyectServer.actualizaruser.actualizarusuariosSoap>, ProyectServer.actualizaruser.actualizarusuariosSoap {
        
        public actualizarusuariosSoapClient() {
        }
        
        public actualizarusuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public actualizarusuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public actualizarusuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public actualizarusuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.actualizaruser.actualizarResponse ProyectServer.actualizaruser.actualizarusuariosSoap.actualizar(ProyectServer.actualizaruser.actualizarRequest request) {
            return base.Channel.actualizar(request);
        }
        
        public ProyectServer.actualizaruser.usuario actualizar(ProyectServer.actualizaruser.usuario user_, string nick_, string pass_) {
            ProyectServer.actualizaruser.actualizarRequest inValue = new ProyectServer.actualizaruser.actualizarRequest();
            inValue.Body = new ProyectServer.actualizaruser.actualizarRequestBody();
            inValue.Body.user_ = user_;
            inValue.Body.nick_ = nick_;
            inValue.Body.pass_ = pass_;
            ProyectServer.actualizaruser.actualizarResponse retVal = ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).actualizar(inValue);
            return retVal.Body.actualizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.actualizarResponse> ProyectServer.actualizaruser.actualizarusuariosSoap.actualizarAsync(ProyectServer.actualizaruser.actualizarRequest request) {
            return base.Channel.actualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.actualizaruser.actualizarResponse> actualizarAsync(ProyectServer.actualizaruser.usuario user_, string nick_, string pass_) {
            ProyectServer.actualizaruser.actualizarRequest inValue = new ProyectServer.actualizaruser.actualizarRequest();
            inValue.Body = new ProyectServer.actualizaruser.actualizarRequestBody();
            inValue.Body.user_ = user_;
            inValue.Body.nick_ = nick_;
            inValue.Body.pass_ = pass_;
            return ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).actualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.actualizaruser.buscarResponse ProyectServer.actualizaruser.actualizarusuariosSoap.buscar(ProyectServer.actualizaruser.buscarRequest request) {
            return base.Channel.buscar(request);
        }
        
        public ProyectServer.actualizaruser.usuario buscar(ProyectServer.actualizaruser.binario bin_, string nick_) {
            ProyectServer.actualizaruser.buscarRequest inValue = new ProyectServer.actualizaruser.buscarRequest();
            inValue.Body = new ProyectServer.actualizaruser.buscarRequestBody();
            inValue.Body.bin_ = bin_;
            inValue.Body.nick_ = nick_;
            ProyectServer.actualizaruser.buscarResponse retVal = ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).buscar(inValue);
            return retVal.Body.buscarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.buscarResponse> ProyectServer.actualizaruser.actualizarusuariosSoap.buscarAsync(ProyectServer.actualizaruser.buscarRequest request) {
            return base.Channel.buscarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.actualizaruser.buscarResponse> buscarAsync(ProyectServer.actualizaruser.binario bin_, string nick_) {
            ProyectServer.actualizaruser.buscarRequest inValue = new ProyectServer.actualizaruser.buscarRequest();
            inValue.Body = new ProyectServer.actualizaruser.buscarRequestBody();
            inValue.Body.bin_ = bin_;
            inValue.Body.nick_ = nick_;
            return ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).buscarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.actualizaruser.insertarResponse ProyectServer.actualizaruser.actualizarusuariosSoap.insertar(ProyectServer.actualizaruser.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public ProyectServer.actualizaruser.binario insertar(ProyectServer.actualizaruser.binario bin_, string nick_, string pass_) {
            ProyectServer.actualizaruser.insertarRequest inValue = new ProyectServer.actualizaruser.insertarRequest();
            inValue.Body = new ProyectServer.actualizaruser.insertarRequestBody();
            inValue.Body.bin_ = bin_;
            inValue.Body.nick_ = nick_;
            inValue.Body.pass_ = pass_;
            ProyectServer.actualizaruser.insertarResponse retVal = ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).insertar(inValue);
            return retVal.Body.insertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.insertarResponse> ProyectServer.actualizaruser.actualizarusuariosSoap.insertarAsync(ProyectServer.actualizaruser.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.actualizaruser.insertarResponse> insertarAsync(ProyectServer.actualizaruser.binario bin_, string nick_, string pass_) {
            ProyectServer.actualizaruser.insertarRequest inValue = new ProyectServer.actualizaruser.insertarRequest();
            inValue.Body = new ProyectServer.actualizaruser.insertarRequestBody();
            inValue.Body.bin_ = bin_;
            inValue.Body.nick_ = nick_;
            inValue.Body.pass_ = pass_;
            return ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.actualizaruser.eliminarResponse ProyectServer.actualizaruser.actualizarusuariosSoap.eliminar(ProyectServer.actualizaruser.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public ProyectServer.actualizaruser.binario eliminar(ProyectServer.actualizaruser.binario bin_, string nick_) {
            ProyectServer.actualizaruser.eliminarRequest inValue = new ProyectServer.actualizaruser.eliminarRequest();
            inValue.Body = new ProyectServer.actualizaruser.eliminarRequestBody();
            inValue.Body.bin_ = bin_;
            inValue.Body.nick_ = nick_;
            ProyectServer.actualizaruser.eliminarResponse retVal = ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).eliminar(inValue);
            return retVal.Body.eliminarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.actualizaruser.eliminarResponse> ProyectServer.actualizaruser.actualizarusuariosSoap.eliminarAsync(ProyectServer.actualizaruser.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.actualizaruser.eliminarResponse> eliminarAsync(ProyectServer.actualizaruser.binario bin_, string nick_) {
            ProyectServer.actualizaruser.eliminarRequest inValue = new ProyectServer.actualizaruser.eliminarRequest();
            inValue.Body = new ProyectServer.actualizaruser.eliminarRequestBody();
            inValue.Body.bin_ = bin_;
            inValue.Body.nick_ = nick_;
            return ((ProyectServer.actualizaruser.actualizarusuariosSoap)(this)).eliminarAsync(inValue);
        }
    }
}
