//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectServer.graficadorjuegos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="listajuegos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class listajuegos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficadorjuegos.juego primeroField;
        
        private int contField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.graficadorjuegos.juego primero {
            get {
                return this.primeroField;
            }
            set {
                if ((object.ReferenceEquals(this.primeroField, value) != true)) {
                    this.primeroField = value;
                    this.RaisePropertyChanged("primero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int cont {
            get {
                return this.contField;
            }
            set {
                if ((this.contField.Equals(value) != true)) {
                    this.contField = value;
                    this.RaisePropertyChanged("cont");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="juego", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class juego : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userbaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string oponenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficadorjuegos.juego siguienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.graficadorjuegos.juego anteriorField;
        
        private int desplegadasField;
        
        private int sobrevivientesField;
        
        private int destruidasField;
        
        private int ganoField;
        
        private int contField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userbase {
            get {
                return this.userbaseField;
            }
            set {
                if ((object.ReferenceEquals(this.userbaseField, value) != true)) {
                    this.userbaseField = value;
                    this.RaisePropertyChanged("userbase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oponente {
            get {
                return this.oponenteField;
            }
            set {
                if ((object.ReferenceEquals(this.oponenteField, value) != true)) {
                    this.oponenteField = value;
                    this.RaisePropertyChanged("oponente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.graficadorjuegos.juego siguiente {
            get {
                return this.siguienteField;
            }
            set {
                if ((object.ReferenceEquals(this.siguienteField, value) != true)) {
                    this.siguienteField = value;
                    this.RaisePropertyChanged("siguiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ProyectServer.graficadorjuegos.juego anterior {
            get {
                return this.anteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.anteriorField, value) != true)) {
                    this.anteriorField = value;
                    this.RaisePropertyChanged("anterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int desplegadas {
            get {
                return this.desplegadasField;
            }
            set {
                if ((this.desplegadasField.Equals(value) != true)) {
                    this.desplegadasField = value;
                    this.RaisePropertyChanged("desplegadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int sobrevivientes {
            get {
                return this.sobrevivientesField;
            }
            set {
                if ((this.sobrevivientesField.Equals(value) != true)) {
                    this.sobrevivientesField = value;
                    this.RaisePropertyChanged("sobrevivientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int destruidas {
            get {
                return this.destruidasField;
            }
            set {
                if ((this.destruidasField.Equals(value) != true)) {
                    this.destruidasField = value;
                    this.RaisePropertyChanged("destruidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int gano {
            get {
                return this.ganoField;
            }
            set {
                if ((this.ganoField.Equals(value) != true)) {
                    this.ganoField = value;
                    this.RaisePropertyChanged("gano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int cont {
            get {
                return this.contField;
            }
            set {
                if ((this.contField.Equals(value) != true)) {
                    this.contField = value;
                    this.RaisePropertyChanged("cont");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="graficadorjuegos.graficarlistadejuegosSoap")]
    public interface graficarlistadejuegosSoap {
        
        // CODEGEN: Generating message contract since element name listado from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        ProyectServer.graficadorjuegos.graficarResponse graficar(ProyectServer.graficadorjuegos.graficarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/graficar", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.graficadorjuegos.graficarResponse> graficarAsync(ProyectServer.graficadorjuegos.graficarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficar", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.graficadorjuegos.graficarRequestBody Body;
        
        public graficarRequest() {
        }
        
        public graficarRequest(ProyectServer.graficadorjuegos.graficarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.graficadorjuegos.listajuegos listado;
        
        public graficarRequestBody() {
        }
        
        public graficarRequestBody(ProyectServer.graficadorjuegos.listajuegos listado) {
            this.listado = listado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class graficarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="graficarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.graficadorjuegos.graficarResponseBody Body;
        
        public graficarResponse() {
        }
        
        public graficarResponse(ProyectServer.graficadorjuegos.graficarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class graficarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string graficarResult;
        
        public graficarResponseBody() {
        }
        
        public graficarResponseBody(string graficarResult) {
            this.graficarResult = graficarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface graficarlistadejuegosSoapChannel : ProyectServer.graficadorjuegos.graficarlistadejuegosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class graficarlistadejuegosSoapClient : System.ServiceModel.ClientBase<ProyectServer.graficadorjuegos.graficarlistadejuegosSoap>, ProyectServer.graficadorjuegos.graficarlistadejuegosSoap {
        
        public graficarlistadejuegosSoapClient() {
        }
        
        public graficarlistadejuegosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public graficarlistadejuegosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficarlistadejuegosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public graficarlistadejuegosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.graficadorjuegos.graficarResponse ProyectServer.graficadorjuegos.graficarlistadejuegosSoap.graficar(ProyectServer.graficadorjuegos.graficarRequest request) {
            return base.Channel.graficar(request);
        }
        
        public string graficar(ProyectServer.graficadorjuegos.listajuegos listado) {
            ProyectServer.graficadorjuegos.graficarRequest inValue = new ProyectServer.graficadorjuegos.graficarRequest();
            inValue.Body = new ProyectServer.graficadorjuegos.graficarRequestBody();
            inValue.Body.listado = listado;
            ProyectServer.graficadorjuegos.graficarResponse retVal = ((ProyectServer.graficadorjuegos.graficarlistadejuegosSoap)(this)).graficar(inValue);
            return retVal.Body.graficarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.graficadorjuegos.graficarResponse> ProyectServer.graficadorjuegos.graficarlistadejuegosSoap.graficarAsync(ProyectServer.graficadorjuegos.graficarRequest request) {
            return base.Channel.graficarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.graficadorjuegos.graficarResponse> graficarAsync(ProyectServer.graficadorjuegos.listajuegos listado) {
            ProyectServer.graficadorjuegos.graficarRequest inValue = new ProyectServer.graficadorjuegos.graficarRequest();
            inValue.Body = new ProyectServer.graficadorjuegos.graficarRequestBody();
            inValue.Body.listado = listado;
            return ((ProyectServer.graficadorjuegos.graficarlistadejuegosSoap)(this)).graficarAsync(inValue);
        }
    }
}
