//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectServer.tabfinal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class mo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int sizexField;
        
        private int sizeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.nivel primeroField;
        
        private int varianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tiempoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.ArrayOfInt navesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sizex {
            get {
                return this.sizexField;
            }
            set {
                if ((this.sizexField.Equals(value) != true)) {
                    this.sizexField = value;
                    this.RaisePropertyChanged("sizex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sizey {
            get {
                return this.sizeyField;
            }
            set {
                if ((this.sizeyField.Equals(value) != true)) {
                    this.sizeyField = value;
                    this.RaisePropertyChanged("sizey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.tabfinal.nivel primero {
            get {
                return this.primeroField;
            }
            set {
                if ((object.ReferenceEquals(this.primeroField, value) != true)) {
                    this.primeroField = value;
                    this.RaisePropertyChanged("primero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int variante {
            get {
                return this.varianteField;
            }
            set {
                if ((this.varianteField.Equals(value) != true)) {
                    this.varianteField = value;
                    this.RaisePropertyChanged("variante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tiempo {
            get {
                return this.tiempoField;
            }
            set {
                if ((object.ReferenceEquals(this.tiempoField, value) != true)) {
                    this.tiempoField = value;
                    this.RaisePropertyChanged("tiempo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user1 {
            get {
                return this.user1Field;
            }
            set {
                if ((object.ReferenceEquals(this.user1Field, value) != true)) {
                    this.user1Field = value;
                    this.RaisePropertyChanged("user1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string user2 {
            get {
                return this.user2Field;
            }
            set {
                if ((object.ReferenceEquals(this.user2Field, value) != true)) {
                    this.user2Field = value;
                    this.RaisePropertyChanged("user2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ProyectServer.tabfinal.ArrayOfInt naves {
            get {
                return this.navesField;
            }
            set {
                if ((object.ReferenceEquals(this.navesField, value) != true)) {
                    this.navesField = value;
                    this.RaisePropertyChanged("naves");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nivel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class nivel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.coord horizontalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.coord verticalField;
        
        private int valField;
        
        private int sizexField;
        
        private int sizeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.nivel supField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.nivel infField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.tabfinal.coord horizontal {
            get {
                return this.horizontalField;
            }
            set {
                if ((object.ReferenceEquals(this.horizontalField, value) != true)) {
                    this.horizontalField = value;
                    this.RaisePropertyChanged("horizontal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.tabfinal.coord vertical {
            get {
                return this.verticalField;
            }
            set {
                if ((object.ReferenceEquals(this.verticalField, value) != true)) {
                    this.verticalField = value;
                    this.RaisePropertyChanged("vertical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int val {
            get {
                return this.valField;
            }
            set {
                if ((this.valField.Equals(value) != true)) {
                    this.valField = value;
                    this.RaisePropertyChanged("val");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int sizex {
            get {
                return this.sizexField;
            }
            set {
                if ((this.sizexField.Equals(value) != true)) {
                    this.sizexField = value;
                    this.RaisePropertyChanged("sizex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int sizey {
            get {
                return this.sizeyField;
            }
            set {
                if ((this.sizeyField.Equals(value) != true)) {
                    this.sizeyField = value;
                    this.RaisePropertyChanged("sizey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ProyectServer.tabfinal.nivel sup {
            get {
                return this.supField;
            }
            set {
                if ((object.ReferenceEquals(this.supField, value) != true)) {
                    this.supField = value;
                    this.RaisePropertyChanged("sup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ProyectServer.tabfinal.nivel inf {
            get {
                return this.infField;
            }
            set {
                if ((object.ReferenceEquals(this.infField, value) != true)) {
                    this.infField = value;
                    this.RaisePropertyChanged("inf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="coord", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class coord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.pos primeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ProyectServer.tabfinal.pos primero {
            get {
                return this.primeroField;
            }
            set {
                if ((object.ReferenceEquals(this.primeroField, value) != true)) {
                    this.primeroField = value;
                    this.RaisePropertyChanged("primero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class pos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int valField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.unit primeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.pos siguienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.pos anteriorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int val {
            get {
                return this.valField;
            }
            set {
                if ((this.valField.Equals(value) != true)) {
                    this.valField = value;
                    this.RaisePropertyChanged("val");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ProyectServer.tabfinal.unit primero {
            get {
                return this.primeroField;
            }
            set {
                if ((object.ReferenceEquals(this.primeroField, value) != true)) {
                    this.primeroField = value;
                    this.RaisePropertyChanged("primero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ProyectServer.tabfinal.pos siguiente {
            get {
                return this.siguienteField;
            }
            set {
                if ((object.ReferenceEquals(this.siguienteField, value) != true)) {
                    this.siguienteField = value;
                    this.RaisePropertyChanged("siguiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ProyectServer.tabfinal.pos anterior {
            get {
                return this.anteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.anteriorField, value) != true)) {
                    this.anteriorField = value;
                    this.RaisePropertyChanged("anterior");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="unit", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class unit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        private int xField;
        
        private int yField;
        
        private int nivelField;
        
        private int movField;
        
        private int rminField;
        
        private int rmaxField;
        
        private int hpField;
        
        private int atkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        private int existeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.unit izqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.unit derField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.unit arribaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.unit abajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.unit supField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectServer.tabfinal.unit infField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int nivel {
            get {
                return this.nivelField;
            }
            set {
                if ((this.nivelField.Equals(value) != true)) {
                    this.nivelField = value;
                    this.RaisePropertyChanged("nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int mov {
            get {
                return this.movField;
            }
            set {
                if ((this.movField.Equals(value) != true)) {
                    this.movField = value;
                    this.RaisePropertyChanged("mov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int rmin {
            get {
                return this.rminField;
            }
            set {
                if ((this.rminField.Equals(value) != true)) {
                    this.rminField = value;
                    this.RaisePropertyChanged("rmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int rmax {
            get {
                return this.rmaxField;
            }
            set {
                if ((this.rmaxField.Equals(value) != true)) {
                    this.rmaxField = value;
                    this.RaisePropertyChanged("rmax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int hp {
            get {
                return this.hpField;
            }
            set {
                if ((this.hpField.Equals(value) != true)) {
                    this.hpField = value;
                    this.RaisePropertyChanged("hp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int atk {
            get {
                return this.atkField;
            }
            set {
                if ((this.atkField.Equals(value) != true)) {
                    this.atkField = value;
                    this.RaisePropertyChanged("atk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int existe {
            get {
                return this.existeField;
            }
            set {
                if ((this.existeField.Equals(value) != true)) {
                    this.existeField = value;
                    this.RaisePropertyChanged("existe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ProyectServer.tabfinal.unit izq {
            get {
                return this.izqField;
            }
            set {
                if ((object.ReferenceEquals(this.izqField, value) != true)) {
                    this.izqField = value;
                    this.RaisePropertyChanged("izq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ProyectServer.tabfinal.unit der {
            get {
                return this.derField;
            }
            set {
                if ((object.ReferenceEquals(this.derField, value) != true)) {
                    this.derField = value;
                    this.RaisePropertyChanged("der");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ProyectServer.tabfinal.unit arriba {
            get {
                return this.arribaField;
            }
            set {
                if ((object.ReferenceEquals(this.arribaField, value) != true)) {
                    this.arribaField = value;
                    this.RaisePropertyChanged("arriba");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ProyectServer.tabfinal.unit abajo {
            get {
                return this.abajoField;
            }
            set {
                if ((object.ReferenceEquals(this.abajoField, value) != true)) {
                    this.abajoField = value;
                    this.RaisePropertyChanged("abajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ProyectServer.tabfinal.unit sup {
            get {
                return this.supField;
            }
            set {
                if ((object.ReferenceEquals(this.supField, value) != true)) {
                    this.supField = value;
                    this.RaisePropertyChanged("sup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public ProyectServer.tabfinal.unit inf {
            get {
                return this.infField;
            }
            set {
                if ((object.ReferenceEquals(this.infField, value) != true)) {
                    this.infField = value;
                    this.RaisePropertyChanged("inf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tabfinal.tablerofinalSoap")]
    public interface tablerofinalSoap {
        
        // CODEGEN: Generating message contract since element name ingreso from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/finalsobrevivientes", ReplyAction="*")]
        ProyectServer.tabfinal.finalsobrevivientesResponse finalsobrevivientes(ProyectServer.tabfinal.finalsobrevivientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/finalsobrevivientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ProyectServer.tabfinal.finalsobrevivientesResponse> finalsobrevivientesAsync(ProyectServer.tabfinal.finalsobrevivientesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class finalsobrevivientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="finalsobrevivientes", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.tabfinal.finalsobrevivientesRequestBody Body;
        
        public finalsobrevivientesRequest() {
        }
        
        public finalsobrevivientesRequest(ProyectServer.tabfinal.finalsobrevivientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class finalsobrevivientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.tabfinal.mo ingreso;
        
        public finalsobrevivientesRequestBody() {
        }
        
        public finalsobrevivientesRequestBody(ProyectServer.tabfinal.mo ingreso) {
            this.ingreso = ingreso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class finalsobrevivientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="finalsobrevivientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProyectServer.tabfinal.finalsobrevivientesResponseBody Body;
        
        public finalsobrevivientesResponse() {
        }
        
        public finalsobrevivientesResponse(ProyectServer.tabfinal.finalsobrevivientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class finalsobrevivientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProyectServer.tabfinal.mo finalsobrevivientesResult;
        
        public finalsobrevivientesResponseBody() {
        }
        
        public finalsobrevivientesResponseBody(ProyectServer.tabfinal.mo finalsobrevivientesResult) {
            this.finalsobrevivientesResult = finalsobrevivientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tablerofinalSoapChannel : ProyectServer.tabfinal.tablerofinalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tablerofinalSoapClient : System.ServiceModel.ClientBase<ProyectServer.tabfinal.tablerofinalSoap>, ProyectServer.tabfinal.tablerofinalSoap {
        
        public tablerofinalSoapClient() {
        }
        
        public tablerofinalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tablerofinalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tablerofinalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tablerofinalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectServer.tabfinal.finalsobrevivientesResponse ProyectServer.tabfinal.tablerofinalSoap.finalsobrevivientes(ProyectServer.tabfinal.finalsobrevivientesRequest request) {
            return base.Channel.finalsobrevivientes(request);
        }
        
        public ProyectServer.tabfinal.mo finalsobrevivientes(ProyectServer.tabfinal.mo ingreso) {
            ProyectServer.tabfinal.finalsobrevivientesRequest inValue = new ProyectServer.tabfinal.finalsobrevivientesRequest();
            inValue.Body = new ProyectServer.tabfinal.finalsobrevivientesRequestBody();
            inValue.Body.ingreso = ingreso;
            ProyectServer.tabfinal.finalsobrevivientesResponse retVal = ((ProyectServer.tabfinal.tablerofinalSoap)(this)).finalsobrevivientes(inValue);
            return retVal.Body.finalsobrevivientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectServer.tabfinal.finalsobrevivientesResponse> ProyectServer.tabfinal.tablerofinalSoap.finalsobrevivientesAsync(ProyectServer.tabfinal.finalsobrevivientesRequest request) {
            return base.Channel.finalsobrevivientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectServer.tabfinal.finalsobrevivientesResponse> finalsobrevivientesAsync(ProyectServer.tabfinal.mo ingreso) {
            ProyectServer.tabfinal.finalsobrevivientesRequest inValue = new ProyectServer.tabfinal.finalsobrevivientesRequest();
            inValue.Body = new ProyectServer.tabfinal.finalsobrevivientesRequestBody();
            inValue.Body.ingreso = ingreso;
            return ((ProyectServer.tabfinal.tablerofinalSoap)(this)).finalsobrevivientesAsync(inValue);
        }
    }
}
